### ISSUE TITLE
Fix Flaky Test

### ISSUE THREAD

**Issue by macieknajbar** [bartossh/scribe#10]
When running test by `cargo test` we get result from test
```
test dictionary::tests::test_serialize_save_read ... FAILED
```
and sometimes
```
test dictionary::tests::test_serialize_save_read ... ok
```

**Comment by bartossh** [comment]
I cannot make the test fail. All the time dictionary::tests::test_serialize_save_read passes.

**Comment by macieknajbar** [comment]
I found a root cause. Two tests were referring to the same file. One test was overriding file that the first test was reading.
